version: "3.2"
services:
 webserver:
  image: webserver
  build: webserver/
  networks:
    internal:
      aliases:
        - webserver
  volumes:
    - type: bind
      source: /webdata
      target: /var/www/html
 database:
  image: database
  build: database/
  healthcheck:
      test: mysqladmin -uroot -proot ping
      interval: 5s
      timeout: 2s
      retries: 30
  networks:
    internal:
      aliases:
        - database
  restart: always
  ports:
    - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: root
  volumes:
   - type: bind
     source: /mariadb
     target: /var/lib/mysql   
 scripthandler:
  image: scripthandler
  build: scripthandler/
  networks:
    internal:
      aliases:
        - scripthandler
  volumes:
    - type: bind
      source: /webdata
      target: /var/www/html
 redis:
  image: redis
  build: redis/
  networks:
    internal:
      aliases:
        - redis
  ports:
    - "6379:6379"
 elasticsearch:
  image: elasticsearch
  build: elasticsearch/
  networks:
    internal:
      aliases:
        - elasticsearch
  ports:
    - "9200:9200"
 loadbalancer:
  image: loadbalancer
  build: loadbalancer/
  networks:
    internal:
      aliases:
        - loadbalancer
  ports:
   - "80:80"
 sw-cli-tools:
  image: sw-cli-tools
  build: sw-cli-tools/
  networks:
    internal:
      aliases:
        - sw-cli-tools
  environment:
    PATH: $PATH:/var/www/sw-cli-tools/bin
  volumes:
    - type: bind
      source: /webdata
      target: /var/www/html
volumes:
  webdata:
networks:
  internal:
